### ISSUE TITLE
Adding some tests to the repo

### ISSUE THREAD

**Issue by medic-code** [kkotsche1/Counseling-Dataset-Creation-Finetuning-ALPACA#3]
Not sure if you've had this on your mind but it would be good to include some simple unit and integration tests to your repo. 

See 

https://realpython.com/python-testing/#testing-your-code - if you've not come across testing before.

**Comment by kkotsche1** [comment]
I think this would go far beyond the scope of this repo which is merely intended to provide the code I used to train the model. The goal of this repo was not to provide a psychotherapy chatbot for out-of-the-box use but merely to share code to LoRA train a model. 

If something like this were built for production you would be right on with your assessment.

**Comment by medic-code** [comment]
Yep no worries! It's good to get in the habit of testing your code even if it's hobby projects. 

Even just doing a couple of unit tests on the scraping scripts/merging scripts. 

It also builds in good coding practices if you wanted to take your journey further.
