### ISSUE TITLE
Remove chromedriver file

### ISSUE THREAD

**Issue by medic-code** [kkotsche1/Counseling-Dataset-Creation-Finetuning-ALPACA#5]
Its a little unusual to put a exe file in a repo (you can imagine the security concerns with something like this!), you could in the README.md specify which version of chromedriver that needs to be installed prior to installing the required packages or provide a script that downloads the correct version for other developers that needs to be run for setting it up.

**Comment by kkotsche1** [comment]
Fair point! Will adjust the repo accordingly :)
